---
- hosts: all # 指定伺服器部分: 所有伺服器
  remote_user: user # 遠端登入時的目前使用者
  become_user: user # 需要提權時的目前使用者
  become: true # 提高權限
  vars:
    docker_version: "6.1.3"
    project_src: "/home/user/repo/2023_schoolResearch_ClientApp/src/demo"
    project_name: app_fontend
  tasks:
    - name: "task1: Install Docker SDK for Python"
      ansible.builtin.pip:
        name: 
          - docker=={{ docker_version }}
          - docker-compose
    - name: "task2: Delete previous containers and images"
      community.docker.docker_container:
        name: "{{ item }}"
        state: absent
      loop:
        - master-cont
        - user-cont
      ignore_errors: true
    - name: "task3: build a fontend"
      community.docker.docker_compose_v2:
        project_src: "{{ project_src }}"
        project_name: "{{ project_name }}"
        build: "policy"
        state: present
    
